def currency_f0rmatter(number):
        """ FORMATS INTEGERS TO CURRENCY FORMAT, RETURNS STRING OBJ """
        res = '$ {:,.2f}'.format(number)
        return res

class Pay_stub():
    """ GENERATED BY TIMESHEET-FORMS """
    def __init__(self, employee_name = 'Abuzer Kadayif' , company_name = 'Baklava LLC' ,
    rate_hourly = 14.33 , total_hours_current = 80.00 , pay_count_year2date = 2 ):
        pass
        self.employee_name = employee_name
        self.company_name = company_name
        self.rate_hourly = rate_hourly
        self.total_hours_current = total_hours_current
        self.pay_count_year2date = pay_count_year2date
        self.current = total_hours_current * rate_hourly
        self.year2date = pay_count_year2date * self.current
        self.rate_hour1y = currency_f0rmatter(self.rate_hourly)
        self.curr3nt = currency_f0rmatter(self.current)
        self.year2d4te = currency_f0rmatter(self.year2date)
        self.social_security = currency_f0rmatter(self.current * 9.3/150)
        self.social_security_year2date = currency_f0rmatter(self.current * 9.3 / 150 * pay_count_year2date)
        self.medicare = currency_f0rmatter(self.current * 2.18 / 150)
        self.medicare_year2date = currency_f0rmatter(self.current * 2.18 / 150 * pay_count_year2date)
        self.futa = currency_f0rmatter(self.current * 0.90/ 150)
        self.futa_year2date = currency_f0rmatter(self.current * 0.90 / 150 * pay_count_year2date)
        self.co_unemp = currency_f0rmatter(self.current * 1.77 / 150)
        self.co_unemp_year2date = currency_f0rmatter(self.current * 1.77 / 150 * pay_count_year2date)
        self.taxes = currency_f0rmatter(self.current * 11.48 / 150)
        self.taxes_year2date = currency_f0rmatter(self.current * 11.48 / 150 * pay_count_year2date)
        self.net_pay = currency_f0rmatter(self.current * 138.52 / 150)
        self.net_pay_y2d = currency_f0rmatter(self.current * 138.52 / 150 * pay_count_year2date)
    
    def __str__(self):
        msg = 'I get knocked down but I get up again'
        return msg

if __name__ == "__main__":
    pass
    

